### ISSUE TITLE
Как поправить форматирование prettier'a в vscode?

### ISSUE THREAD

**Issue by p4rs1f41** [Dolgik89/-media-screen#2]
![image](https://user-images.githubusercontent.com/21338809/50169104-f6140780-02fd-11e9-98e8-4f1c00d985c7.png)

**Comment by Dolgik89** [comment]
Я не совсем понял вопроса! но то что на скрине работать не будет... если указываешь ширину цифрами тогда w не нужен, просто 1680: -2vw, 1366: -8.5vw и тд
